# Generated by Django 4.2.14 on 2024-07-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='death_of_death',
            new_name='date_of_death',
        ),
    ]
